export const PROPERTY_REPORT_PRICE_CENTS = 300;
export const PROPERTY_REPORT_PLATFORM_SHARE_CENTS = 150;
export const PROPERTY_REPORT_REALTOR_SHARE_CENTS = 150;
export const PROPERTY_REPORT_CURRENCY = "usd";
